application: team-room
version: 1
runtime: python
api_version: 1

default_expiration: "7d"

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/group.png
  upload: static/group.png
- url: /
  script: main.py
- url: /.*
  script: main.py
  login: required