application: team-room
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/group.png
  upload: static/group.png
- url: /.*
  script: holding.py